apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  releaseName: crossplane
  chart:
    spec:
      chart: crossplane
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
  interval: 5m
  install:
    crds: Create
    remediation:
      retries: 10
  upgrade:
    crds: CreateReplace
  values:
    replicas: 1

    deploymentStrategy: RollingUpdate

    image:
      repository: crossplane/crossplane
      tag: v1.5.0
      pullPolicy: IfNotPresent

    nodeSelector: {}
    tolerations: {}
    affinity: {}

    leaderElection: true
    args: {}

    provider:
      packages:
        - crossplane/provider-azure:v0.17.1
        - crossplane/provider-helm:v0.9.0

    configuration:
      packages: []

    imagePullSecrets:
    - dockerhub

    rbacManager:
      deploy: true
      skipAggregatedClusterRoles: false
      replicas: 1
      managementPolicy: All
      leaderElection: true
      args: {}
      nodeSelector: {}
      tolerations: {}
      affinity: {}

    priorityClassName: ""

    resourcesCrossplane:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 256Mi

    securityContextCrossplane:
      runAsUser: 65532
      runAsGroup: 65532
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true

    packageCache:
      medium: ""
      sizeLimit: 5Mi
      pvc: ""

    resourcesRBACManager:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

    securityContextRBACManager:
      runAsUser: 65532
      runAsGroup: 65532
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true

    metrics:
      enabled: false

    extraEnvVarsCrossplane: {}

    extraEnvVarsRBACManager: {}


