apiVersion: network.azure.crossplane.io/v1alpha3
kind: VirtualNetwork
metadata:
  name: gitops-aks-crossplane-vnet
spec:
  resourceGroupNameRef:
    name: gitops-aks-crossplane-rg
  location: northeurope
  properties:
    addressSpace:
      addressPrefixes:
        - 10.2.0.0/16
  providerConfigRef:
    name: gitops-azure

--- 

apiVersion: network.azure.crossplane.io/v1alpha3
kind: Subnet
metadata:
  name: gitops-aks-crossplane-vnet-sub
spec:
  resourceGroupNameRef:
    name: gitops-aks-crossplane-rg
  virtualNetworkNameRef:
    name: gitops-aks-crossplane-vnet
  properties:
    addressPrefix: 10.2.0.0/24
  providerConfigRef:
    name: gitops-azure


