apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: helm-ingress-nginx
spec:
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: "4.0.13"
    namespace: ingress-nginx
  providerConfigRef:
    name: gitops-aks-helm-provider
