# Source: aks-factory/templates/azure-provider.yaml
apiVersion: v1
kind: Secret
metadata:
    name: gitops-azure-credentials
    namespace: crossplane-system
type: Opaque
data:
    credentials: ENC[AES256_GCM,data:bwbAUDTuXLjyX2DzE+ljj/5wf2XTBlt5XzeoV6rHFLCqyriQ5Uk9o2893gHrognhA3ho1fcbMLFNAO9hIVUkjmX+XuuXJWQjmyCU8Gow2FaPt4SMKeKmseSvg9CpAS8PuNjU+pSxevUSyQ1tFZVMXWNxzSHiMV30E/qC6kssORNGv6QsFsZf6zF7gwU3JyWfezDRerCtmf4M3KzTiyyRvXLSW2sNwlglB5CBDvUqAkatvPeVHmjbZA2tArj4JIXaljxuO1Abv/T8hLhqLfWGjZQAdUXTYorj5fHweuSZ8lBYKcj29C0QR55/U7E1zqLEdtPabXraHarac2yLbsLhXk/elJb3y8SSjaGeFSKQZXkC6mpoicc8ClzgdqpxUEMlUnL356AfQUi6or2GOH61O1EK8fF5eHpxg4fIx4tkPmkDGbb9sMsJp4y5/JYj73mTNR5hjeiPOvHSDj1mKNXgfNIzJZ318TmdCOP2DW2YHIemtPdEMUG4xfqSAyudtD2AXDNCwUy2TnCXA83LEK8Ta7sxtgpfOWmE1RsVIklFJG6gjbG1Am38tvdE4qXeoJfHUmv0vr9lzJ0JNbLg+3csFGZwBDPBiaHI641a9dLtCwDMEKYv+wiwh8NgycOIdkisqs+W6Pfrq8Tk3OpxjNZwXbUFeCY5XMfXXrAfIgndDkxEbKcYh+hl/WyTgJ3d74txC3EpxLOH9xauHRJSn0yRZqYkhA9W7pxrz0FkEGXE7ARZIvaZjDtlFQ1/58+ZbqswgsH4MMOcsAMhjWn/+SfDXo78Q2UJ27HZt2R9uNyJWkh2Q8iyW+m+kpwS0ibR+uKOJEOYuv1lHjtE946T5mtbO02pMo6tIBXA6ubBYPVDT/+QnbMcg0XHF8s9jEROHVuzXNgeXi5Y1rRYhDu1VG9j4MTr6ddWttZsq+Il3zGuhZ1zhTmNuGPO1M1LXeNLw/h0XBlTitTNajSfreURqlJF+UVN+6r+BM9n9nL3NvRZM6pemy4SI+NzDS3rTUQsZq7BhbTrcOWfELPj7/bC9Sv+ybrownv4fjh8GKlOi4cl9yZZZ2YubBOdcgE82HJ3845NRbnf8OKFRKut3+8jOOIvcg==,iv:28IHfpmlfPYToRtY12H04jBw+1EgYWYuuCJCuYhwpC4=,tag:VP1h56vqc6/+NLn1EAPTLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-06T17:44:38Z"
    mac: ENC[AES256_GCM,data:pXx+pzJdh7Gt8xZN6Xep8X0lmZDa1tcPyLlaZyvVXL2xyx03jx5ntz5unhOTUBbBK6W7XE1KQE8JDQhkQzFYryFer3nNniOBPN67A5KFmyw8+vbonbZk2A3KlC4gQ2u5psQkgAYhs5a6lV1vJzbhYRukYWqg3Sq97sulLykUXzU=,iv:cFrx55LAbY66wYwfiETEyIC+EwAfoVYoTsW1yyah5/c=,tag:TwtlefePrulNN91rEw2otg==,type:str]
    pgp:
        - created_at: "2021-12-06T17:44:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA4IA3NtUDv+xAQv+Mo453eEX36JwjwSFwATmZBo8MXf2deO94oGsl35hyVCK
            XHNxY9ua5SV/tW+DB0uwdiheOGcpqVBTwjty4NUiLVkND97BooNdLD0wHrGDigiR
            meG4aSrCPl+SzcqIpMTQI3f+H0mpADgnKCdzIedrqoF4OLmMT+dDRhJ/I7uWs++c
            kubYwP3Crt0dy3EKcfvu4O4A0ij2bFvPHpBTVL71OM9jxXC8Awso4Uti8XeMG/D3
            co7KQ/IVKapSonNAJebMggYwlYKptKkm8xm9r4vvBQYNBN2rnVtQTgocO6UHP9su
            eLsgUy6Lms45Vaa2dwYVx+e236fYHQQLW4/HgMXbTUrMzEBV55CMON6pWmEO5+av
            v19K/MK1H0HM9ahDUgo3Ky4KX8YiTmIGFndv3DZU++RJAy5QrKDbwhGpjwgF/QRl
            IMekoq+2flW0+TToqVsIfc1Pb8DeftDdsRp8uIVxBPE1QOWQmJVr49skbgMSCVAO
            cys4nMh/L5J3NcODwT8L0l4BjeggKQUuA8yGj4hYxVTL1uBRrKFbDOzLNtJvn+yq
            jKRdlTREJ8g2mDwQeTEclGAqPQ7XizjsniiwhoE8+SX65i86ikeKYV9b7MgQ5j+C
            R0uGfGxSHXFyU/6IBT8s
            =VZnE
            -----END PGP MESSAGE-----
          fp: 5FC2B09291BAA27F366177B3922E467A10BC9C82
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
