apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/crossplane
  - 01-gitops-azure-credentials.yaml
  - 02-providers-config.yaml
  - 03-rg.yaml
  - 04-vnet.yaml
  - 05-subnet.yaml
  - 06-aks.yaml
  - 07-checking-provider-k8s.yaml
  - 07-checking-provider-helm.yaml
patchesStrategicMerge:
  - crossplane-values.yaml
